name: Rust Release

permissions:
  contents: write
  security-events: write

on:
  push:
    tags:
      - "v*"

jobs:
  # ============================================================
  # JOB 1: Security Scan with trivy
  # ============================================================
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy - Table (CRITICAL & HIGH)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          version: "latest"
          format: "table"         
          severity: "CRITICAL,HIGH"
          exit-code: "0"          
          ignore-unfixed: true     
          scanners: "vuln,secret"  

      - name: Run Trivy - SARIF (untuk GitHub Security tab)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          version: "latest"
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
          exit-code: "0"
          ignore-unfixed: true
          scanners: "vuln,secret"

      - name: Upload hasil scan ke GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

  # ============================================================
  # JOB 2: Build & Release 
  # ============================================================
  build:
    needs: trivy-scan
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      # ===== LINUX =====
      - name: Package Linux
        if: runner.os == 'Linux'
        run: |
          mkdir package
          cp target/release/IsJack_tool package/
          cd package
          zip ../IsJack_tool-linux.zip IsJack_tool

      # ===== WINDOWS =====
      - name: Package Windows
        if: runner.os == 'Windows'
        run: |
          mkdir package
          cp target/release/IsJack_tool.exe package/
          cd package
          powershell Compress-Archive IsJack_tool.exe ../IsJack_tool-windows.zip

      # ===== MACOS =====
      - name: Package macOS
        if: runner.os == 'macOS'
        run: |
          mkdir package
          cp target/release/IsJack_tool package/
          cd package
          zip ../IsJack_tool-macos.zip IsJack_tool

      # ===== CHECKSUM =====
      - name: Generate checksums
        run: |
          sha256sum *.zip > checksums.txt || shasum -a 256 *.zip > checksums.txt

      # ===== RELEASE =====
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip
            checksums.txt